apiVersion: enterprise.splunk.com/v4
kind: ClusterManager
metadata:
  name: cm
  annotations:
    kubernetes.io/ingress.class: alb
spec:
  serviceTemplate:
    spec:
      type: LoadBalancer 
  appRepo:
    appSources:
    - location: appframework
      name: apps
      scope: cluster
    appsRepoPollIntervalSeconds: 60
    defaults:
      scope: local
      volumeName: volume_app_repo
    volumes:
    - endpoint: https://s3-us-west-2.amazonaws.com
      name: volume_app_repo
      path: helm-test-c3-with-apps-test
      provider: aws
      region: us-west-2 
      secretRef: s3-secret
      storageType: s3
  smartstore:
    cacheManager:
      evictionPadding: 1024
      evictionPolicy: lru
      hotlistBloomFilterRecencyHours: 360
      hotlistRecencySecs: 86400
      maxCacheSize: 0
      maxConcurrentDownloads: 8
      maxConcurrentUploads: 8
    defaults:
      volumeName: helm-test-c3-with-apps-smartstore-test
    indexes:
    - name: main
      remotePath: $_index_name
      volumeName: helm-test-c3-with-apps-smartstore-test
    - name: cloudwatch
      remotePath: $_index_name
      volumeName: helm-test-c3-with-apps-smartstore-test
    volumes:
    - endpoint: https://s3-us-west-2.amazonaws.com
      name: helm-test-c3-with-apps-smartstore-test
      path: helm-test-c3-with-apps-smartstore-test/smartstore
      secretRef: s3-secret
  livenessInitialDelaySeconds: 300
  readinessInitialDelaySeconds: 10
  etcVolumeStorageConfig:
    ephemeralStorage: false
    storageCapacity: 10Gi
  varVolumeStorageConfig:
    ephemeralStorage: false
    storageCapacity: 100Gi 
