apiVersion: enterprise.splunk.com/v4
kind: Standalone
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: vshctest
spec:
  defaults: |-
    splunk:
      set_search_peers: true
  image: 667741767953.dkr.ecr.us-west-2.amazonaws.com/amod/splunk:cloud
  serviceTemplate:
    spec:
      type: LoadBalancer
  readinessInitialDelaySeconds: 100
  readinessProbe:
    timeoutSeconds: 5
    periodSeconds:  5
    failureThreshold: 3
  livenessInitialDelaySeconds: 300
  livenessProbe:
    timeoutSeconds: 30
    periodSeconds:  30
    failureThreshold:  3
  appRepo: 
    appSources:
    - location: appframework
      name: apps
      scope: local
    appsRepoPollIntervalSeconds: 60
    defaults:
      scope: local
      volumeName: volume_app_repo
    volumes:
    - endpoint: https://s3-us-west-2.amazonaws.com
      name: volume_app_repo
      path: noahappframework
      provider: aws
      region: us-west-2
      secretRef: s3-secret
      storageType: s3
  noahSpec:
    searchHead: true
    noahService:
      uri:  http://afe190b14a50f491db1d4710f62d3412-d8a927b5641e21a8.elb.us-west-2.amazonaws.com:8443
      heartbeatPeriod: 3
      heartbeatAsPercentageOfLease: 25
      tenant: test3
      remoteBundle: s3://noahappframework/test3/smartstore/
      pass4SymmKeyMinLength: 10
      reportIndexDeletion: true
      cacheBucketTimeout: 3
    noahClient: 
      timeoutConnect: 12
      timeoutRead: 12
      timeoutWrite: 12
      retryPolicy: max_count
      maxCountMaxRetriesPerPart: 5
    noahClientBucketSettings:
      retryPolicy: max_count
      maxCountMaxRetriesPerPart: 4
      backoffStrategy: exponential
      backoffStrategyConstantDelay: 500
    noahSettings:
      skipBucketReloadPeriod: 0
      listFrozenBucketPeriod: 0
